name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Create new Next.js project
        run: |
          # Guardar archivos importantes
          mkdir -p /tmp/portfolio-backup
          cp -r app components lib public /tmp/portfolio-backup/
          cp tailwind.config.ts next.config.mjs /tmp/portfolio-backup/
          
          # Crear nuevo proyecto
          npx create-next-app@14.0.3 temp-portfolio --typescript --tailwind --eslint --app --src-dir --import-alias "@/*"
          
          # Restaurar archivos
          rm -rf temp-portfolio/app temp-portfolio/components
          cp -r /tmp/portfolio-backup/* temp-portfolio/
          
          # Mover al directorio principal
          mv temp-portfolio/* .
          mv temp-portfolio/.* . 2>/dev/null || true
          rm -rf temp-portfolio
      
      - name: Install dependencies
        run: npm install
      
      - name: Build with Next.js
        run: npm run build
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

